apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewaydeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gatewayserv
  template:
    metadata:
      labels:
        app: gatewayserv
    spec:
      containers:
        - name: gatewayservcont
          image: gateway
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 300m
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayserv
  labels:
    app: gatewayserv
spec:
  type: ClusterIP
  selector:
    app: gatewayserv
  ports:
    - port: 80
      targetPort: 8080
    
    
