apiVersion: v1
kind: ConfigMap
metadata:
  name: nextjsfrontendconfig
data:
  env: |
    NEXTAUTH_URL=http://localhost:8080/c
    KEYCLOAK_CLIENT_SECRET=vteQUtE6WmjIBN60Mpq3Pw1jOAUANghr
    KEYCLOAK_CLIENT_ID=libmgmt_spring
    KEYCLOAK_REALM=libmanagement
    JWT_ISSUER_URI=http://keycloak/realms/libmanagement
    NEXTAUTH_SECRET=3oJCRKb32emmyhbVU4RhRD8D8dUWAg66XVEwN3XcPl4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjsfrontenddeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjsfrontend
  template:
    metadata:
      labels:
        app: nextjsfrontend
    spec:
      containers:
        - name: nextjsfrontend
          image: nextjsfrontend
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 900m
              memory: 1000Mi
          # volumeMounts:
          #   - name: envfile
          #     mountPath: /app/
          #     readOnly: true
      volumes:
        - name: envfile
          configMap:
            name: nextjsfrontendconfig
            items:
              - key: env          
                path: .env
---
apiVersion: v1
kind: Service
metadata:
  name: nextjsfrontendservice
  labels:
    app: nextjsfrontend
spec:
  selector:
    app: nextjsfrontend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  
