apiVersion: apps/v1
kind: Deployment
meta:
  name: nextjsfrontenddeploy
spec:
  selector:
    matchLabels:
      app: nextjsfrontend
  template:
    metadata:
      labels:
        app: nextjsfrontend
    spec:
      containers:
        - name: nextjsfrontend
          image: nextjsfrontend
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 300m
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nextjsfrontendService
  labels:
    app: nextjsfrontend
spec:
  selector:
    app: nextjsfrontend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  
