apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjsfrontenddeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjsfrontend
  template:
    metadata:
      labels:
        app: nextjsfrontend
    spec:
      containers:
        - name: nextjsfrontend
          image: nextjsfrontend
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 900m
              memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nextjsfrontendservice
  labels:
    app: nextjsfrontend
spec:
  selector:
    app: nextjsfrontend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  
