spring:
  application:
    name: booksmgmtserv
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: bookManagementDB
      username: user
      password: password
      authentication-database: admin
