spring:
  application:
    name: booksmgmtserv
  data:
    mongodb:
      host: 192.168.1.143
      port: 27018
      database: bookManagementDB
      username: user
      password: password
      authentication-database: admin
