spring:
  application:
    name: booksmgmtserv
  data:
    mongodb:
      host: mongodb.docker.internal
      port: 27018
      database: bookManagementDB
      username: user
      password: password
      authentication-database: admin
