services:
  postgresql:
    image: postgres:12.21-bookworm
    ports:
      - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - psql_vol:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - libmgmt-netwk

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 9090:8080

  mongodb:
    image: mongo:8.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27018:27017
    networks:
      - libmgmt-netwk

  nextjsfrontend:
    build:
      context: ./nextjsfrontend
    ports: 
      - 3000:3000
    networks:
      - libmgmt-netwk
      


volumes:
  psql_vol:

networks:
  libmgmt-netwk:
    external: true
  
