apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: libmanagement
build:
  artifacts:
    - image: bookmgmtserv
      context: booksmgmtserv
      docker:
        dockerfile: Dockerfile
    - image: keycloak
      context: keycloak
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    inputDigest: {}
  local:
    concurrency: 0
manifests:
  kustomize:
    paths:
      - k8smanifests
