spring:
  application:
    name: gateway
  cloud:
    gateway:
        routes:
          - id: usermgmt
            uri: http://usermgmt
            predicates:
              - Path=/umgmt/**
            filters:
              - RewritePath=/umgmt/?(?<segment>.*), /$\{segment}
          - id: booksmgmtserv
            uri: http://bookmgmtserv
            predicates:
              - Path=/api/books/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak/realms/libmanagement