services:
  postgresql:
    image: postgres:12.21-bookworm
    ports:
      - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloakdb
    volumes:
      - psql_vol:/var/lib/postgresql

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 9090:8080


volumes:
  psql_vol:
