spring:
  application:
    name: authservice
  datasource:
    url: jdbc:postgresql://localhost:5432/bookloan
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak/realms/libmanagement
keycloak:
  server-url: http://localhost:8081
  realm: libmanagement
  client-id: libmgmt_spring
  client-secret: vteQUtE6WmjIBN60Mpq3Pw1jOAUANghr
services:
  bookmgmtserv: http://bookmgmtserv