spring:
  application:
    name: authservice
  datasource:
    url: jdbc:postgresql://localhost:5432/bookloan
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


keycloak:
  server-url: http://localhost:8081
  realm: libmanagement
  client-id: libmgmt_spring_cli
  client-secret: 9Knb1Pq4L4N7YI1bZcdT2fsTXD8QBOhO

services:
  bookgmgmtserv: http://bookmgmtserv